root: true

extends: 'eslint:all'

parserOptions:
  ecmaVersion: 6

env:
  node: true
  es6: true

rules:
  # Possible errors.
  no-await-in-loop: error
  no-cond-assign: error
  no-console: off
  no-constant-condition: error
  no-control-regex: error
  no-debugger: error
  no-dupe-args: error
  no-dupe-keys: error
  no-duplicate-case: error
  no-empty-character-class: error
  no-empty: error
  no-ex-assign: error
  no-extra-boolean-cast: error
  no-extra-parens: error
  no-extra-semi: error
  no-func-assign: error
  no-inner-declarations: [error, both]
  no-invalid-regexp: error
  no-irregular-whitespace: error
  no-obj-calls: error
  no-prototype-builtins: error
  no-regex-spaces: error
  no-sparse-arrays: error
  no-template-curly-in-string: error
  no-unexpected-multiline: error
  no-unreachable: error
  no-unsafe-finally: error
  no-unsafe-negation: error
  use-isnan: error
  valid-jsdoc: error
  valid-typeof: error

  # Best practices.
  accessor-pairs: error
  array-callback-return: error
  block-scoped-var: error
  class-methods-use-this: error
  complexity: [error, 2]
  consistent-return: error
  curly: [error, multi, consistent]
  default-case: error
  dot-location: [error, property]
  dot-notation: error
  eqeqeq: [error, smart]
  guard-for-in: error
  no-alert: error
  no-caller: error
  no-case-declarations: error
  no-div-regex: error
  no-else-return: error
  no-empty-function: error
  no-empty-pattern: error
  no-eq-null: error
  no-eval: error
  no-extend-native: error
  no-extra-bind: error
  no-extra-label: error
  no-fallthrough: error
  no-floating-decimal: error
  no-global-assign: error
  no-implicit-coercion: error
  no-implicit-globals: error
  no-implied-eval: error
  no-invalid-this: error
  no-iterator: error
  no-labels: error
  no-lone-blocks: error
  no-loop-func: error
  no-magic-numbers:
    - error
    - ignore: [0, 1, 2]
      enforceConst: true
      ignoreArrayIndexes: true
  no-multi-spaces: error
  no-multi-str: error
  no-new-func: error
  no-new-wrappers: error
  no-new: error
  no-octal-escape: error
  no-octal: error
  no-param-reassign: error
  no-proto: error
  no-redeclare: error
  no-restricted-properties: off
  no-return-assign: error
  no-return-await: error
  no-script-url: error
  no-self-assign: error
  no-self-compare: error
  no-sequences: error
  no-throw-literal: error
  no-unmodified-loop-condition: error
  no-unused-expressions: error
  no-unused-labels: error
  no-useless-call: error
  no-useless-concat: error
  no-useless-escape: error
  no-useless-return: error
  no-void: error
  no-warning-comments: error
  no-with: error
  radix: error
  require-await: error
  vars-on-top: error
  wrap-iife: error
  yoda: error

  # Strict mode.
  strict: [error, global]

  # Variables.
  init-declarations: error
  no-catch-shadow: error
  no-delete-var: error
  no-label-var: error
  no-restricted-globals: off
  no-shadow-restricted-names: error
  no-shadow: error
  no-undef-init: error
  no-undef: error
  no-undefined: error
  no-unused-vars: error
  no-use-before-define: error

  # Node.js.
  callback-return: error
  global-require: error
  handle-callback-err: error
  no-mixed-requires: error
  no-new-require: error
  no-path-concat: error
  no-process-env: error
  no-process-exit: off
  no-restricted-modules: off
  no-sync: error

  # Stylistic issues.
  array-bracket-spacing: error
  block-spacing: error
  brace-style: [error, 1tbs, allowSingleLine: true]
  camelcase: error
  capitalized-comments: off
  comma-dangle: error
  comma-spacing: error
  comma-style: error
  computed-property-spacing: [error, never]
  consistent-this: [error, self]
  eol-last: error
  func-call-spacing: error
  func-name-matching: error
  func-names: error
  func-style: [error, declaration]
  id-blacklist: off
  id-length: error
  id-match: off
  indent:
    - error
    - 2
    - VariableDeclarator: { var: 2, let: 2, const: 3 }
      ArrayExpression: first
  jsx-quotes: off
  key-spacing: error
  keyword-spacing: error
  line-comment-position: off
  linebreak-style: error
  lines-around-comment: error
  lines-around-directive: error
  max-depth: error
  max-len: [error, code: 79, ignoreUrls: true]
  max-lines: [error, max: 1000]
  max-nested-callbacks: [error, max: 3]
  max-params: error
  max-statements-per-line: [error, max: 3]
  max-statements: error
  multiline-ternary: off
  new-cap: error
  new-parens: error
  newline-after-var: off
  newline-before-return: off
  newline-per-chained-call: error
  no-array-constructor: error
  no-bitwise: error
  no-continue: off
  no-inline-comments: off
  no-lonely-if: error
  no-mixed-operators: error
  no-mixed-spaces-and-tabs: error
  no-multiple-empty-lines: [error, { max: 3, maxEOF: 1, maxBOF: 0 }]
  no-negated-condition: error
  no-nested-ternary: error
  no-new-object: error
  no-plusplus: off
  no-restricted-syntax: off
  no-tabs: error
  no-ternary: off
  no-trailing-spaces: error
  no-underscore-dangle: off
  no-unneeded-ternary: error
  no-whitespace-before-property: error
  object-curly-newline: error
  object-curly-spacing: [error, always]
  object-property-newline: [error, allowMultiplePropertiesPerLine: true]
  one-var-declaration-per-line: error
  one-var: off
  operator-assignment: error
  operator-linebreak: error
  padded-blocks: [error, classes: always]
  quote-props: [error, as-needed]
  quotes: [error, single]
  require-jsdoc: off
  semi-spacing: error
  semi: error
  sort-keys: off
  sort-vars: [error, ignoreCase: true]
  space-before-blocks: error
  space-before-function-paren: [error, never]
  space-in-parens: error
  space-infix-ops: error
  space-unary-ops: error
  spaced-comment: error
  unicode-bom: error
  wrap-regex: error

  # ECMAScript 6.
  arrow-body-style: error
  arrow-parens: [error, as-needed]
  arrow-spacing: error
  constructor-super: error
  generator-star-spacing: error
  no-class-assign: error
  no-confusing-arrow: error
  no-const-assign: error
  no-dupe-class-members: error
  no-duplicate-imports: error
  no-new-symbol: error
  no-restricted-imports: off
  no-this-before-super: error
  no-useless-computed-key: error
  no-useless-constructor: error
  no-useless-rename: error
  no-var: error
  object-shorthand: error
  prefer-arrow-callback: error
  prefer-const: error
  prefer-numeric-literals: error
  prefer-rest-params: error
  prefer-spread: error
  prefer-template: error
  require-yield: error
  rest-spread-spacing: error
  sort-imports: error
  symbol-description: error
  template-curly-spacing: error
  yield-star-spacing: error
