plugins: [stylelint-csstree-validator]

rules:
  # Colour
  color-hex-case: lower
  color-hex-length: short
  color-named: null
  color-no-hex: null
  color-no-invalid-hex: true

  # Font Familiy
  font-family-name-quotes: always-where-recommended
  font-family-no-duplicate-names: true

  # Font weight
  font-weight-notation: named-where-possible

  # Function
  function-blacklist: null
  function-calc-no-unspaced-operator: true
  function-comma-newline-after: always-multi-line
  function-comma-newline-before: never-multi-line
  function-comma-space-after: always-single-line
  function-comma-space-before: never
  function-linear-gradient-no-nonstandard-direction: true
  function-max-empty-lines: 0
  function-name-case: lower
  function-parentheses-newline-inside: null
  function-parentheses-space-inside: never
  function-url-data-uris: null
  function-url-no-scheme-relative: null
  function-url-quotes: never
  function-url-scheme-whitelist: null
  function-whitelist: null
  function-whitespace-after: always

  # Number
  number-leading-zero: never
  number-max-precision: 3
  number-no-trailing-zeros: true

  # String
  string-no-newline: true
  string-quotes: single

  # Length
  length-zero-no-unit: true

  # Time
  time-no-imperceptible: true

  # Unit
  unit-blacklist: null
  unit-case: lower
  unit-no-unknown: true
  unit-whitelist: [px, em, rem, '%', ms]

  # Value
  value-keyword-case: lower
  value-no-vendor-prefix: null

  # Value List
  value-list-comma-newline-after: always-multi-line
  value-list-comma-newline-before: never-multi-line
  value-list-comma-space-after: always-single-line
  value-list-comma-space-before: never
  value-list-max-empty-lines: 0

  # Custom Property
  custom-property-empty-line-before: null
  custom-property-no-outside-root: true
  custom-property-pattern: null

  # Shorthand Property
  shorthand-property-no-redundant-values: true

  # Property
  property-blacklist: null
  property-case: lower
  property-no-unknown: true
  property-no-vendor-prefix: true
  property-whitelist: null

  # Keyframe Declaration
  keyframe-declaration-no-important: true

  # Declaration
  declaration-bang-space-after: never
  declaration-bang-space-before: always
  declaration-colon-newline-after: null
  declaration-colon-space-after: always-single-line
  declaration-colon-space-before: never
  declaration-empty-line-before: null
  declaration-no-important: null
  declaration-property-unit-blacklist: null
  declaration-property-unit-whitelist: null
  declaration-property-value-blacklist: null
  declaration-property-value-whitelist: null

  # Declaration Block
  declaration-block-no-duplicate-properties: true
  declaration-block-no-ignored-properties: true
  declaration-block-no-redundant-longhand-properties: true
  declaration-block-no-shorthand-property-overrides: true
  declaration-block-properties-order: null
  declaration-block-semicolon-newline-after: always-multi-line
  declaration-block-semicolon-newline-before: never-multi-line
  declaration-block-semicolon-space-after: always-single-line
  declaration-block-semicolon-space-before: never
  declaration-block-single-line-max-declarations: null
  declaration-block-trailing-semicolon: always

  # Block
  block-closing-brace-empty-line-before: never
  block-closing-brace-newline-after: always
  block-closing-brace-newline-before: always
  block-closing-brace-space-after: always-single-line
  block-closing-brace-space-before: always-single-line
  block-no-empty: true
  block-no-single-line: true
  block-opening-brace-newline-after: always
  block-opening-brace-newline-before: null
  block-opening-brace-space-after: always-single-line
  block-opening-brace-space-before: always-single-line

  # Selector
  selector-attribute-brackets-space-inside: never
  selector-attribute-operator-blacklist: null
  selector-attribute-operator-space-after: never
  selector-attribute-operator-space-before: never
  selector-attribute-operator-whitelist: null
  selector-attribute-quotes: always
  selector-class-pattern: null
  selector-combinator-space-after: always
  selector-combinator-space-before: always
  selector-descendant-combinator-no-non-space: true
  selector-id-pattern: null
  selector-max-compound-selectors: 3
  selector-max-specificity: null
  selector-nested-pattern: null
  selector-no-attribute: null
  selector-no-combinator: null
  selector-no-empty: true
  selector-no-id: true
  selector-no-qualifying-type: null
  selector-no-type: null
  selector-no-universal: null
  selector-no-vendor-prefix: true
  selector-pseudo-class-blacklist: null
  selector-pseudo-class-case: lower
  selector-pseudo-class-no-unknown: true
  selector-pseudo-class-parentheses-space-inside: never
  selector-pseudo-class-whitelist: null
  selector-pseudo-element-case: lower
  selector-pseudo-element-colon-notation: double
  selector-pseudo-element-no-unknown: true
  selector-root-no-composition: true
  selector-type-case: lower
  selector-type-no-unknown: true
  selector-max-empty-lines: 0

  # Selector List
  selector-list-comma-newline-after: null
  selector-list-comma-newline-before: never-multi-line
  selector-list-comma-space-after: always-single-line
  selector-list-comma-space-before: never

  # Root Rule
  root-no-standard-properties: true

  # Rule
  rule-nested-empty-line-before: null
  rule-non-nested-empty-line-before: null

  # Media Feature
  media-feature-colon-space-after: always
  media-feature-colon-space-before: never
  media-feature-name-blacklist: null
  media-feature-name-case: lower
  media-feature-name-no-unknown: true
  media-feature-name-no-vendor-prefix: true
  media-feature-name-whitelist: null
  media-feature-no-missing-punctuation: true
  media-feature-parentheses-space-inside: never
  media-feature-range-operator-space-after: always
  media-feature-range-operator-space-before: always

  # Custom Media
  custom-media-pattern: null

  # Media Query List
  media-query-list-comma-newline-after: always-multi-line
  media-query-list-comma-newline-before: never-multi-line
  media-query-list-comma-space-after: always-single-line
  media-query-list-comma-space-before: never

  # At-Rule
  at-rule-blacklist: null
  at-rule-empty-line-before: null
  at-rule-name-case: lower
  at-rule-name-newline-after: always-multi-line
  at-rule-name-space-after: null
  at-rule-no-unknown: true
  at-rule-no-vendor-prefix: true
  at-rule-semicolon-newline-after: always
  at-rule-whitelist: null

  # Stylelint-Disable Comment
  stylelint-disable-reason: null

  # Comment
  comment-empty-line-before: null
  comment-no-empty: true
  comment-whitespace-inside: always
  comment-word-blacklist: null

  # General / Sheet
  indentation: [2, ignore: [inside-parens]]
  max-empty-lines: 2
  max-line-length: 79
  max-nesting-depth: 3
  no-browser-hacks: true
  no-descending-specificity: null
  no-duplicate-selectors: true
  no-empty-source: true
  no-eol-whitespace: true
  no-extra-semicolons: true
  no-indistinguishable-colors: null
  no-invalid-double-slash-comments: true
  no-missing-end-of-source-newline: true
  no-unknown-animations: true
  no-unsupported-browser-features: null

  # CSSTree-Validator Plugin
  csstree/validator: true
