plugins: [stylelint-csstree-validator]

rules:
  # Possible Errors -----------------------------------------------------------

  # Colour
  color-no-invalid-hex: true

  # Font Familiy
  font-family-no-duplicate-names: true
  font-family-no-missing-generic-family-keyword: true

  # Function
  function-calc-no-invalid: true
  function-calc-no-unspaced-operator: true
  function-linear-gradient-no-nonstandard-direction: true

  # String
  string-no-newline: true

  # Unit
  unit-no-unknown: true

  # Property
  property-no-unknown: true

  # Keyframe Declaration
  keyframe-declaration-no-important: true

  # Declaration Block
  declaration-block-no-duplicate-properties: true
  declaration-block-no-shorthand-property-overrides: true

  # Block
  block-no-empty: true

  # Selector
  selector-pseudo-class-no-unknown: true
  selector-pseudo-element-no-unknown: true
  selector-type-no-unknown: true

  # Media Feature
  media-feature-name-no-unknown: true

  # At-Rule
  at-rule-no-unknown: true

  # Comment
  comment-no-empty: true

  # General / Sheet
  no-descending-specificity: null
  no-duplicate-at-import-rules: true
  no-duplicate-selectors: true
  no-empty-source: true
  no-extra-semicolons: true
  no-invalid-double-slash-comments: true

  # Limit Language Features ---------------------------------------------------

  # Colour
  color-named: null
  color-no-hex: null

  # Function
  function-blacklist: null
  function-url-no-scheme-relative: null
  function-url-scheme-blacklist: null
  function-url-scheme-whitelist: null
  function-whitelist: null

  # Keyframes
  keyframes-name-pattern: null

  # Number
  number-max-precision: 3

  # Time
  time-min-milliseconds: 150

  # Unit
  unit-blacklist: null
  unit-whitelist: [px, em, rem, '%', ms]

  # Shorthand Property
  shorthand-property-no-redundant-values: true

  # Value
  value-no-vendor-prefix: null

  # Custom Property
  custom-property-pattern: null

   # Property
  property-blacklist: null
  property-no-vendor-prefix: true
  property-whitelist: null

  # Declaration
  declaration-block-no-redundant-longhand-properties: true
  declaration-no-important: null
  declaration-property-unit-blacklist: null
  declaration-property-unit-whitelist: null
  declaration-property-value-blacklist: null
  declaration-property-value-whitelist: null

  # Declaration Block
  declaration-block-single-line-max-declarations: null

  # Selector
  selector-attribute-operator-blacklist: null
  selector-attribute-operator-whitelist: null
  selector-class-pattern: null
  selector-combinator-blacklist: null
  selector-combinator-whitelist: null
  selector-id-pattern: null
  selector-max-attribute: 1
  selector-max-class: 2
  selector-max-combinators: 2
  selector-max-compound-selectors: 3
  selector-max-empty-lines: 0
  selector-max-id: 1
  selector-max-pseudo-class: 1
  selector-max-specificity: null
  selector-max-type: 3
  selector-max-universal: 1
  selector-nested-pattern: null
  selector-no-qualifying-type: null
  selector-no-vendor-prefix: true
  selector-pseudo-class-blacklist: null
  selector-pseudo-class-whitelist: null
  selector-pseudo-element-blacklist: null
  selector-pseudo-element-whitelist: null

  # Media Feature
  media-feature-name-blacklist: null
  media-feature-name-no-vendor-prefix: true
  media-feature-name-value-whitelist: null
  media-feature-name-whitelist: null

  # Custom Media
  custom-media-pattern: null

  # At-Rule
  at-rule-blacklist: null
  at-rule-no-vendor-prefix: true
  at-rule-property-requirelist: null
  at-rule-whitelist: null

  # Comment
  comment-word-blacklist: null

  # General / Sheet
  max-nesting-depth: 3
  no-unknown-animations: true

  # Stylistic Issues ----------------------------------------------------------

  # Colour
  color-hex-case: lower
  color-hex-length: short

  # Font Familiy
  font-family-name-quotes: always-where-recommended

  # Font Weight
  font-weight-notation: named-where-possible

  # Function
  function-comma-newline-after: always-multi-line
  function-comma-newline-before: never-multi-line
  function-comma-space-after: always-single-line
  function-comma-space-before: never
  function-max-empty-lines: 0
  function-name-case: lower
  function-parentheses-newline-inside: null
  function-parentheses-space-inside: never
  function-url-quotes: never
  function-whitespace-after: always

  # Number
  number-leading-zero: never
  number-no-trailing-zeros: true

  # String
  string-quotes: single

  # Length
  length-zero-no-unit: true

  # Unit
  unit-case: lower

  # Value
  value-keyword-case: lower

  # Value List
  value-list-comma-newline-after: always-multi-line
  value-list-comma-newline-before: never-multi-line
  value-list-comma-space-after: always-single-line
  value-list-comma-space-before: never
  value-list-max-empty-lines: 0

  # Custom Property
  custom-property-empty-line-before: null

  # Property
  property-case: lower

  # Declaration
  declaration-bang-space-after: never
  declaration-bang-space-before: always
  declaration-colon-newline-after: null
  declaration-colon-space-after: always-single-line
  declaration-colon-space-before: never
  declaration-empty-line-before: null

  # Declaration Block
  declaration-block-semicolon-newline-after: always-multi-line
  declaration-block-semicolon-newline-before: never-multi-line
  declaration-block-semicolon-space-after: always-single-line
  declaration-block-semicolon-space-before: never
  declaration-block-trailing-semicolon: always

  # Block
  block-closing-brace-empty-line-before: never
  block-closing-brace-newline-after: always
  block-closing-brace-newline-before: always
  block-closing-brace-space-after: always-single-line
  block-closing-brace-space-before: always-single-line
  block-opening-brace-newline-after: always
  block-opening-brace-newline-before: null
  block-opening-brace-space-after: always-single-line
  block-opening-brace-space-before: always-single-line

  # Selector
  selector-attribute-brackets-space-inside: never
  selector-attribute-operator-space-after: never
  selector-attribute-operator-space-before: never
  selector-attribute-quotes: always
  selector-combinator-space-after: always
  selector-combinator-space-before: always
  selector-descendant-combinator-no-non-space: true
  selector-pseudo-class-case: lower
  selector-pseudo-class-parentheses-space-inside: never
  selector-pseudo-element-case: lower
  selector-pseudo-element-colon-notation: double
  selector-type-case: lower

  # Selector List
  selector-list-comma-newline-after: null
  selector-list-comma-newline-before: never-multi-line
  selector-list-comma-space-after: always-single-line
  selector-list-comma-space-before: never

  # Rule
  rule-empty-line-before: null

  # Media Feature
  media-feature-colon-space-after: always
  media-feature-colon-space-before: never
  media-feature-name-case: lower
  media-feature-parentheses-space-inside: never
  media-feature-range-operator-space-after: always
  media-feature-range-operator-space-before: always

  # Media Query List
  media-query-list-comma-newline-after: always-multi-line
  media-query-list-comma-newline-before: never-multi-line
  media-query-list-comma-space-after: always-single-line
  media-query-list-comma-space-before: never

  # At-Rule
  at-rule-empty-line-before: null
  at-rule-name-case: lower
  at-rule-name-newline-after: always-multi-line
  at-rule-name-space-after: null
  at-rule-semicolon-newline-after: always
  at-rule-semicolon-space-before: never

  # Comment
  comment-empty-line-before: null
  comment-whitespace-inside: always

  # General / Sheet
  indentation: [2, ignore: [inside-parens]]
  linebreaks: unix
  max-empty-lines: 2
  max-line-length: 79
  no-eol-whitespace: true
  no-missing-end-of-source-newline: true
  no-empty-first-line: true

  # Plugins -------------------------------------------------------------------

  # CSSTree-Validator Plugin
  csstree/validator: true
