# Build settings.
source: app
destination: dist/manual-jekyll-build
include: [.nojekyll]
kramdown:
  # GitHub Flavored Markdown.
  input: GFM
  hard_wrap: false
gems:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll/tagging
  # Sitemap plugin must be last to cover other plugins's (possible) output.
  - jekyll-sitemap
  - liquid_pluralize
permalink: pretty

# Default page layouts.
defaults:
  - scope:
      type: pages
    values:
      schema: "http://schema.org/WebPage"
      og_prefix: "website: http://ogp.me/ns/website#"
      og_type: website
  - scope:
      type: posts
    values:
      layout: post
      comments: true
      schema: "http://schema.org/BlogPosting"
      og_prefix: "article: http://ogp.me/ns/article#"
      og_type: article

# Pagination.
paginate: 5

# Web feed (jekyll-feed).
feed:
  path: atom.xml
  # Jekyll-feed also makes use of url, name, description and author variables.

# Tagging (jekyll-tagging).
tag_page_layout: tag-page
tag_page_dir: tag

# Custom variables.
url: https://arkfps.github.io
name: &sitename The Hermetic Vault
title: *sitename
description: A miscellanea of C++ programming techniques.
tagline: typedef typename template
keywords: [C++, Programming]
topic: Software Development
author: Pavel Frolov
email: eW91cmVtYWlsQHlvdXJkb21haW4uY29t

disqus_shortname: arkfps
google_analytics_id: UA-58552086-1
github_profile: https://github.com/arkfps
linkedin_profile: https://www.linkedin.com/in/psfrolov
facebook:
  profile: https://www.facebook.com/psfrolov
  id: 100005735232020
twitter:
  profile: https://twitter.com/arkfps
  site_id: &twitter_site_id 4133911523
  creator_id: *twitter_site_id
