# Build.
permalink: pretty
paginate: 5
gems:
  - jekyll-sitemap
  - jekyll-feed
  - jemoji

# Serving.
baseurl: /

# Reading.
exclude: [Gemfile, Gemfile.lock, start-server.cmd, THIRD-PARTY.txt]

# Default layouts.
defaults:
  - scope:
      type: posts
    values:
      layout: post
      comments: true
  - scope:
      path: posts-by-tag
    values:
      layout: posts-by-tag    

# Feed.
feed:
  path: atom.xml

# Custom variables.
title: &id1 arkfps
name: *id1
disqus_shortname: *id1
description: Programming Blog
tagline: “O(1) complexity, baby! Now we’re cooking!”
author: Pavel Frolov
url: http://thehermeticvault.com
github_profile: https://github.com/arkfps
linkedin_profile: https://www.linkedin.com/in/psfrolov
