# Build settings.
permalink: pretty
paginate: 5
gems:
  - jekyll-sitemap
  - jekyll-feed
  - jemoji

# Default layouts.
defaults:
  - scope:
      type: "posts"
    values:
      layout: "post"
      comments: true

baseurl: "/"      

exclude: [Gemfile, Gemfile.lock, start-server.cmd, THIRD-PARTY.TXT]

# Sitewide custom variables.
title: &id1 "arkfps"
author: "Pavel Frolov"
disqus_shortname: *id1
description: "programming blog"
tagline: "“O(1) complexity, baby! Now we’re cooking!”"
url: "https://arkfps.github.io"
github_profile: https://github.com/arkfps
linkedin_profile: https://www.linkedin.com/in/psfrolov

# Feed settings.
feed:
  path: atom.xml
name: *id1
 