# Build settings.
source: app
destination: dist/manual-jekyll-build
include: [.nojekyll, .gitattributes]
exclude: ['*.puml']
plugins:  # in processing order
  - liquid_pluralize
  - liquid_reading_time
  - jekyll/tagging
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
permalink: /:categories/:title
strict_front_matter: true
liquid:
  error_mode: strict
  strict_filters: true
  strict_variables: false
kramdown:
  footnote_backlink: ↑

# Default page layouts.
defaults:
  - scope:
      type: pages
    values:
      layout: page
      schema: https://schema.org/WebPage
      og_prefix: 'website: http://ogp.me/ns/website#'
      og_type: website
  - scope:
      type: posts
    values:
      layout: post
      category: software-development
      comments: true
      schema: https://schema.org/BlogPosting
      og_prefix: 'article: http://ogp.me/ns/article#'
      og_type: article
  - scope:
      path: tag
    values:
      sitemap: false  # do not index tag pages

# Pagination (jekyll-paginate).
paginate: 10

# Web feed (jekyll-feed).
feed:
  path: feed.xml
  # Jekyll-feed also makes use of url, name, description, and author variables.

# Tagging (jekyll-tagging).
tag_page_layout: tag-page
tag_page_dir: tag

# Custom variables.
fqdn: TheHermeticVault.com
url: &site_url https://thehermeticvault.com
name: &sitename The Hermetic Vault
title: *sitename
description: >-
  A miscellanea of software development techniques: C++, generic programming,
  design patterns, CI, and more.
tagline: typedef typename template
keywords: [C++, Programming, Software, Development]
topic: Software Development
creator:
  first_name: Pavel
  last_name: Frolov
  full_name: &creator_full_name Pavel Frolov
  username: psfrolov
author: *creator_full_name  # for jekyll-feed plugin

theme_colour: '#ac4142'

disqus:
  shortname: arkfps
github:
  profile: https://github.com/psfrolov
linkedin:
  profile: https://www.linkedin.com/profile/view?id=AAIAAA9ggBMBXzMR8ZdzqQx1k_pNBI8nu3o85Z4
facebook:
  profile: https://www.facebook.com/100005735232020
  profile_id: 100005735232020
  app_id: 416481208892021
twitter:
  profile: https://twitter.com/intent/user?user_id=4133911523
  user_id: &twitter_user_id 4133911523
  site_id: *twitter_user_id
  creator_id: *twitter_user_id
