# Build settings.
permalink: pretty
paginate: 3
gems:
  - jekyll-sitemap
  - jemoji
  
# Default layouts.
defaults:
  - scope:
      type: "posts"
    values:
      layout: "post"
      comments: true

baseurl: "/"      
      
# Sitewide custom variables.
title: &id1 "arkfps"
author: *id1
disqus_shortname: *id1
tagline: "programming blog"
description: "Random technical stuff."
url: "https://arkfps.github.io"
github_profile: https://github.com/arkfps
